# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2

updates:
  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: uv
    directory: /                     # oder Unterverzeichnis, falls Projekt nicht im Root liegt
    schedule:
      interval: weekly              # oder "daily", "monthly"
  - package-ecosystem: docker
    directory: /  # Pfad zu deinem Dockerfile
    schedule:
      interval: weekly
    allow:
      - dependency-type: all
