{{- $files := .Files }}
{{- $caCrt := "" }}
{{- /* Prefer direct value over file reference */ -}}
{{- if $.Values.tls.caCrt }}
{{- $caCrt = $.Values.tls.caCrt }}
{{- else if $.Values.tls.caCrtFile }}
{{- $caCrt = $files.Get $.Values.tls.caCrtFile }}
{{- end }}
{{- if and $.Values.tls $caCrt }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fairagro-advanced-middleware-api-chart.fullname" . }}-ca-secret
type: Opaque
stringData:
  ca.crt: {{ $caCrt | toYaml | indent 2 }}
{{- end }}
