{{- $files := .Files }}
{{- if and $.Values.tls $.Values.tls.caCrtFile }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fairagro-advanced-middleware-api-chart.fullname" . }}-ca-secret
type: Opaque
data:
  ca.crt: {{ $files.Get $.Values.tls.caCrtFile | b64enc }}
{{- end }}
