{{- if .Values.api.ingress.mtlsEnabled }}
{{- $files := .Files }}
{{- $caCrt := "" }}
{{- /* Prefer direct value over file reference */ -}}
{{- if $.Values.api.tls.caCrt }}
{{- $caCrt = $.Values.api.tls.caCrt }}
{{- else if $.Values.api.tls.caCrtFile }}
{{- $caCrt = $files.Get $.Values.api.tls.caCrtFile }}
{{- end }}
{{- if and $.Values.api.tls $caCrt }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fairagro-advanced-middleware-api-chart.fullname" . }}-ca-secret
type: Opaque
stringData:
  ca.crt: {{ $caCrt | toYaml | indent 2 }}
{{- end }}
{{- end }}
