{{- if .Values.api.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "fairagro-advanced-middleware-api-chart.fullname" . }}
  labels:
    {{- include "fairagro-advanced-middleware-api-chart.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "fairagro-advanced-middleware-api-chart.fullname" . }}
  minReplicas: {{ .Values.api.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.api.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.api.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.api.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.api.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.api.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}

{{- if and .Values.celery.worker.enabled .Values.celery.worker.autoscaling.enabled .Values.rabbitmq.enabled .Values.redis.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "fairagro-advanced-middleware-api-chart.fullname" . }}-celery-worker
  labels:
    {{- include "fairagro-advanced-middleware-api-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: celery-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "fairagro-advanced-middleware-api-chart.fullname" . }}-celery-worker
  minReplicas: {{ .Values.celery.worker.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.celery.worker.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.celery.worker.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.celery.worker.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.celery.worker.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.celery.worker.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
