{{- $files := .Files }}
{{- $serverCrt := "" }}
{{- $serverKey := "" }}
{{- /* Prefer direct values over file references */ -}}
{{- if $.Values.tls.serverCrt }}
{{- $serverCrt = $.Values.tls.serverCrt }}
{{- else if $.Values.tls.serverCrtFile }}
{{- $serverCrt = $files.Get $.Values.tls.serverCrtFile }}
{{- end }}
{{- if $.Values.tls.serverKey }}
{{- $serverKey = $.Values.tls.serverKey }}
{{- else if $.Values.tls.serverKeyFile }}
{{- $serverKey = $files.Get $.Values.tls.serverKeyFile }}
{{- end }}
{{- if and $.Values.tls (and $serverCrt $serverKey) }}
{{- range $.Values.ingress.tls }}
{{ if .secretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fairagro-advanced-middleware-api-chart.fullname" $ }}-{{ .secretName }}
type: kubernetes.io/tls
stringData:
  tls.crt: {{ $serverCrt | quote }}
  tls.key: {{ $serverKey | quote }}
{{- end }}
{{- end }}
{{- end }}
