{{- $files := .Files }}
{{- $serverCrt := "" }}
{{- $serverKey := "" }}
{{- /* Prefer direct values over file references */ -}}
{{- if $.Values.api.tls.serverCrt }}
{{- $serverCrt = $.Values.api.tls.serverCrt }}
{{- else if $.Values.api.tls.serverCrtFile }}
{{- $serverCrt = $files.Get $.Values.api.tls.serverCrtFile }}
{{- end }}
{{- if $.Values.api.tls.serverKey }}
{{- $serverKey = $.Values.api.tls.serverKey }}
{{- else if $.Values.api.tls.serverKeyFile }}
{{- $serverKey = $files.Get $.Values.api.tls.serverKeyFile }}
{{- end }}
{{- if and $.Values.api.tls (and $serverCrt $serverKey) }}
{{- range $.Values.api.ingress.tls }}
{{ if .secretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fairagro-advanced-middleware-api-chart.fullname" $ }}-{{ .secretName }}
type: kubernetes.io/tls
stringData:
  tls.crt: {{ $serverCrt | toYaml | indent 2 }}
  tls.key: {{ $serverKey | toYaml | indent 2 }}
{{- end }}
{{- end }}
{{- end }}
