{{- $files := .Files }}
{{- if and $.Values.tls (and $.Values.tls.serverCrtFile $.Values.tls.serverKeyFile) }}
{{- range $.Values.ingress.tls }}
{{ if .secretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "advanced-middleware-api.fullname" $ }}-{{ .secretName }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $files.Get $.Values.tls.serverCrtFile | b64enc }}
  tls.key: {{ $files.Get $.Values.tls.serverKeyFile | b64enc }}
{{- end }}
{{- end }}
{{- end }}