"""System tests configuration and fixtures."""

import os
import secrets
import subprocess
import tempfile
import time
from collections.abc import Generator
from pathlib import Path
from typing import Any

import pytest
import yaml
from cryptography import x509
from dotenv import load_dotenv
from fastapi.testclient import TestClient
from gitlab import Gitlab, GitlabError
from testcontainers.core.container import DockerContainer  # type: ignore[import-untyped]
from testcontainers.core.wait_strategies import LogMessageWaitStrategy  # type: ignore[import-untyped]

from middleware.api.api.fastapi_app import Api
from middleware.api.config import Config

# Load environment variables from .env file (generated by load-env.sh)
load_dotenv()

_COUCHDB_IMAGE = "couchdb:3.3"
_COUCHDB_USER = "admin"
_COUCHDB_PORT = 5984

_RABBITMQ_IMAGE = "rabbitmq:3.13-management"
_RABBITMQ_USER = "test-user"
_RABBITMQ_PORT = 5672

_CELERY_APP = "middleware.api.worker.celery_app:celery_app"
_WORKER_STARTUP_TIMEOUT = 60  # seconds


@pytest.fixture(scope="session")
def external_services() -> Generator[dict[str, str], None, None]:
    """Run local CouchDB and RabbitMQ services with random credentials."""
    couchdb_password = secrets.token_hex(16)
    rabbitmq_password = secrets.token_hex(16)

    couchdb_container = (
        DockerContainer(_COUCHDB_IMAGE)
        .with_env("COUCHDB_USER", _COUCHDB_USER)
        .with_env("COUCHDB_PASSWORD", couchdb_password)
        .with_exposed_ports(_COUCHDB_PORT)
        .waiting_for(LogMessageWaitStrategy("Apache CouchDB has started"))
    )
    rabbitmq_container = (
        DockerContainer(_RABBITMQ_IMAGE)
        .with_env("RABBITMQ_DEFAULT_USER", _RABBITMQ_USER)
        .with_env("RABBITMQ_DEFAULT_PASS", rabbitmq_password)
        .with_exposed_ports(_RABBITMQ_PORT)
        .waiting_for(LogMessageWaitStrategy("Server startup complete"))
    )

    with couchdb_container, rabbitmq_container:
        yield {
            "couchdb_url": (
                f"http://{couchdb_container.get_container_host_ip()}:"
                f"{couchdb_container.get_exposed_port(_COUCHDB_PORT)}"
            ),
            "couchdb_user": _COUCHDB_USER,
            "couchdb_password": couchdb_password,
            "rabbitmq_broker_url": (
                f"amqp://{_RABBITMQ_USER}:{rabbitmq_password}@"
                f"{rabbitmq_container.get_container_host_ip()}:"
                f"{rabbitmq_container.get_exposed_port(_RABBITMQ_PORT)}//"
            ),
        }


@pytest.fixture(scope="session")
def config(
    oid: x509.ObjectIdentifier,
    known_rdis: list[str],
    external_services: dict[str, str],
) -> dict[str, Any]:
    """Provide configuration for tests."""
    gitlab_token = os.getenv("GITLAB_API_TOKEN")

    if not gitlab_token:
        pytest.skip(
            "system_external tests require GITLAB_API_TOKEN in environment. "
            "Provide a real token for DataHUB/GitLab access."
        )

    return {
        "log_level": "DEBUG",
        "known_rdis": list(known_rdis),
        "client_auth_oid": oid.dotted_string,
        "require_client_cert": False,
        "gitlab_api": {
            "url": "https://datahub-dev.ipk-gatersleben.de",
            "group": "FAIRagro-advanced-middleware-integration-tests",
            "token": gitlab_token,
        },
        "celery": {
            "broker_url": external_services["rabbitmq_broker_url"],
            "result_backend": os.getenv("CELERY_RESULT_BACKEND", "rpc://"),
        },
        "couchdb": {
            "url": external_services["couchdb_url"],
            "user": external_services["couchdb_user"],
            "password": external_services["couchdb_password"],
        },
    }


@pytest.fixture(scope="session")
def gitlab_api(
    config: dict[str, Any],
) -> Gitlab:  # pylint: disable=redefined-outer-name
    """Provide a Gitlab API client for tests."""
    token = os.getenv("GITLAB_API_TOKEN")
    if not token:
        pytest.skip("system_external tests require GITLAB_API_TOKEN")
    return Gitlab(config["gitlab_api"]["url"], private_token=token)


@pytest.fixture(scope="session")
def gitlab_group(config: dict[str, Any], gitlab_api: Gitlab) -> Any:  # pylint: disable=redefined-outer-name
    """Provide the Gitlab group for tests."""
    try:
        group = gitlab_api.groups.get(config["gitlab_api"]["group"])
        return group
    except GitlabError as e:
        pytest.skip(f"GitLab group {config['gitlab_api']['group']} not found or accessible: {e}")
        return None


@pytest.fixture
def middleware_api(
    config: dict[str, Any],
    external_services: dict[str, str],
    monkeypatch: pytest.MonkeyPatch,
) -> Api:  # pylint: disable=redefined-outer-name
    """Provide the Middleware API instance for full-stack external tests."""
    # Ensure config-wrapper environment overrides use the testcontainer credentials.
    monkeypatch.setenv("COUCHDB_URL", external_services["couchdb_url"])
    monkeypatch.setenv("COUCHDB_USER", external_services["couchdb_user"])
    monkeypatch.setenv("COUCHDB_PASSWORD", external_services["couchdb_password"])
    monkeypatch.setenv("CELERY_BROKER_URL", external_services["rabbitmq_broker_url"])

    config_validated = Config.from_data(config)
    return Api(config_validated)


@pytest.fixture
def client(
    middleware_api: Api,
) -> Generator[TestClient, None, None]:  # pylint: disable=redefined-outer-name
    """Provide a TestClient for the Middleware API."""
    with TestClient(middleware_api.app) as c:
        yield c


@pytest.fixture(scope="session", autouse=True)
def cleanup_gitlab_group(gitlab_group: Any, gitlab_api: Gitlab) -> None:  # pylint: disable=redefined-outer-name
    """Cleanup the Gitlab group before tests."""
    if gitlab_group is None:
        return
    # delete all projects in the group
    for project in gitlab_group.projects.list(all=True):
        try:
            full_project = gitlab_api.projects.get(project.id)
            full_project.delete()
            print(f"Deleted test project: {project.name}")
        except GitlabError as e:
            print(f"Failed to delete project {project.name}: {e}")


@pytest.fixture(scope="session")
def worker_process(
    external_services: dict[str, str],
    config: dict[str, Any],
) -> Generator[None, None, None]:
    """Spawn a real Celery worker that consumes from the testcontainer RabbitMQ.

    The worker is started as a subprocess (no pytest in its sys.modules), so
    celery_app.py loads a proper WorkerConfig from a temporary YAML file
    pointing at the same CouchDB and RabbitMQ testcontainers used by the API.
    """
    gitlab_token = os.getenv("GITLAB_API_TOKEN", "")
    worker_cfg: dict[str, Any] = {
        "couchdb": {
            "url": external_services["couchdb_url"],
            "user": external_services["couchdb_user"],
            "password": external_services["couchdb_password"],
        },
        "celery": {
            "broker_url": external_services["rabbitmq_broker_url"],
            "retry_backoff": False,
            "max_retries": 3,
        },
        "gitlab_api": {
            "url": str(config["gitlab_api"]["url"]),
            "group": config["gitlab_api"]["group"],
            "token": gitlab_token,
        },
    }

    cfg_fd, cfg_path_str = tempfile.mkstemp(suffix=".yaml")
    cfg_path = Path(cfg_path_str)
    with os.fdopen(cfg_fd, "w", encoding="utf-8") as f:
        yaml.dump(worker_cfg, f)

    log_path = cfg_path.with_suffix(".log")
    # Explicitly pass testcontainer credentials so ConfigWrapper env-overrides
    # (e.g. from a loaded .env file) cannot shadow the YAML values.
    env = {
        **os.environ,
        "MIDDLEWARE_API_CONFIG": str(cfg_path),
        "COUCHDB_URL": external_services["couchdb_url"],
        "COUCHDB_USER": external_services["couchdb_user"],
        "COUCHDB_PASSWORD": external_services["couchdb_password"],
        "CELERY_BROKER_URL": external_services["rabbitmq_broker_url"],
    }

    with log_path.open("w", encoding="utf-8") as log_file:
        proc = subprocess.Popen(  # pylint: disable=consider-using-with
            [
                "uv",
                "run",
                "celery",
                "-A",
                _CELERY_APP,
                "worker",
                "--concurrency=2",
                "--loglevel=info",
            ],
            env=env,
            stdout=log_file,
            stderr=subprocess.STDOUT,
        )

    # Poll the log file until the worker emits "ready." or timeout/crash.
    deadline = time.monotonic() + _WORKER_STARTUP_TIMEOUT
    ready = False
    while time.monotonic() < deadline:
        if proc.poll() is not None:
            log_content = log_path.read_text(encoding="utf-8", errors="replace") if log_path.exists() else "(empty)"
            cfg_path.unlink(missing_ok=True)
            log_path.unlink(missing_ok=True)
            pytest.fail(f"Celery worker exited prematurely (rc={proc.returncode}).\nWorker log:\n{log_content}")
        if log_path.exists() and "ready." in log_path.read_text(encoding="utf-8", errors="replace"):
            ready = True
            break
        time.sleep(0.5)

    if not ready:
        log_content = log_path.read_text(encoding="utf-8", errors="replace") if log_path.exists() else "(empty)"
        proc.terminate()
        proc.wait(timeout=15)
        cfg_path.unlink(missing_ok=True)
        log_path.unlink(missing_ok=True)
        pytest.fail(
            f"Celery worker did not become ready within {_WORKER_STARTUP_TIMEOUT}s.\nWorker log:\n{log_content}"
        )

    try:
        yield
    finally:
        proc.terminate()
        try:
            proc.wait(timeout=15)
        except subprocess.TimeoutExpired:
            proc.kill()
        cfg_path.unlink(missing_ok=True)
        log_path.unlink(missing_ok=True)
