name: Check Version Label

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, labeled]

permissions:
  contents: read

jobs:
  check-label:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR for version label
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const allowedLabels = ["major version","minor version","patch version"];
            const pr = context.payload.pull_request;
            if (!pr) {
              core.setFailed("This workflow must be triggered by a pull_request event.");
              return;
            }
            const labels = pr.labels.map(l => l.name);
            const matching = labels.filter(l => allowedLabels.includes(l));
            if (matching.length !== 1) {
              core.setFailed(
                `PR must have exactly one version label: ${allowedLabels.join(", ")}. Found: ${matching.join(", ") || "none"}`
              );
            } else {
              core.info(`Found version label: ${matching[0]}`);
            }
