name: Python Code Check

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  code_check:
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: 3.12

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v5

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Install uv package manager
        run: |
          python -m pip install --upgrade uv setuptools
          uv sync --dev

      - name: Lint with pylint
        run: |
          pylint middleware_api tests

      - name: Test with pytest
        run: |
          pytest tests/unit
