name: Add Version Info to Merge Commit

on:
  pull_request:
    branches: [main]
    types: [closed]

permissions:
  contents: write

env:
  GIT_USER_NAME: GitHub Pipeline
  GIT_USER_EMAIL: github_pipeline@fairagro.net

jobs:
  add-merge-message:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      # Prüfen des Labels für Version Bump
      - name: Determine Version label
        id: version-label
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const allowedLabels = ["major version","minor version","patch version"];
            const pr = context.payload.pull_request;
            const labels = pr.labels.map(l => l.name);
            console.log("Labels on PR:", labels);
            const matching = labels.filter(l => allowedLabels.includes(l));
            console.log("Matching labels:", matching);
            const result = matching[0].replace(" version","");
            console.log("Determined version label:", result);
            core.setOutput("result", result);

      - name: Amend merge commit message
        run: |
          MERGE_COMMIT=$(git log -1 --merges --pretty=format:%H)
          VERSION_LABEL=${{ steps.version-label.outputs.result }}
          git config user.name "${{ env.GIT_USER_NAME }}"
          git config user.email "{{ env.GIT_USER_EMAIL }}"
          git commit --amend -m "$(git log -1 --pretty=%B) +semver: $VERSION_LABEL"
          git push --force
